### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nightflyer88**
- BMP085, BMP180, BMP280, BME280 are supported
- Vario value works now only with pressure sensor
- If a pressure sensor is connected, the relative altitude is
calculated with the air pressure
- 3D distance is now supported (can be set in Jetibox)
- menu improved
- Number of satellites and HDOP are also displayed without FIX

### CODE REVIEW

**Comment by RC-Thoughts** [comment]
I have no plans at the moment for creating nor supporting multisensors, please visit openXsensor for that approach. Therefor closing this request.

**Comment by nightflyer88** [comment]
I do not quite understand your decision. The idea for extending the GPS sensor with the Vario sensor is of course a great thing for sailplanes, so you do not have to install two individual sensors.
After the update, the GPS sensor can also be operated without a pressure sensor.

**Comment by RC-Thoughts** [comment]
One person would like to see sensor X and sensor Y in one unit, other one would like to see X and Z and so on. The decision to keep it within "one sensor - one function" was done by me very early when I begun these small things. 

There is a few basic reasons:
- Variations are too many to maintain
- Variations are too many to support
- There is a very well working multi-sensor alternative available, the openXsensor, no need to reinvent the wheel on that part. Please have a look on that if you are interested in multi-sensors.

My philosophy with DIY-sensors are "cheap, easy to make sensors everyone can make" and to get started with telemetry for a little DIY-time, in this I have succeeded. This is based on surveys, forum-traffic etc.

Then there is the simple fact that maintaining sufficient level of support to users takes a lot of work and time and multisensors would just increase it. After all, this is my hobby and is done on my free time.

**Comment by nightflyer88** [comment]
Of course you are quite right, everyone wants to combine other sensors with each other, and it gets more and more confusing.
If it did you not mind, I create a new topic as an extended version, ok?

**Comment by RC-Thoughts** [comment]
No problem of course, it's open source. The correct way would be to rename it, basically it's "Nightflyers version of RCT GPS", not "RCT GPS version 1.6". not renaming it clearly can make people confused if7when they need support.

**Pull request closed without merging**
